apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-a018"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-a018"
  template:
    metadata:
      labels:
        app: "myakscluster-a018"
    spec:
      containers:
        - name: "myakscluster-a018"
          image: "tmpacr2021.azurecr.io/myakscluster"
          ports:
          - containerPort: 9001