apiVersion: v1
kind: Service
metadata:
    name: "myakscluster-a018"
    labels:
        app: "myakscluster-a018"
spec:
    type: LoadBalancer
    ports:
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: http
    selector:
        app: "myakscluster-a018"